# (PART) Tidyverse {-}

# La colección de paquetes tidyverse {#tidyverse}

***En preparación...***

En los capítulos de esta parte se pretende realizar una breve introducción al *ecosistema* [**Tidyverse**](https://dplyr.tidyverse.org), una colección de paquetes diseñados de forma uniforme (con la misma filosofía y estilo) para trabajar conjuntamente.

La referencia recomendada para usuarios de R que deseen iniciarse en el uso de estos paquetes es: 

Wickham, H., y Grolemund, G. (2016). *[R for data science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz)*, [online-castellano](https://es.r4ds.hadley.nz), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do).

El paquete [`tidyverse`](https://tidyverse.tidyverse.org) está diseñado para facilitar la instalación y carga de los paquetes principales de la colección tidyverse con un solo comando.
Al instalar este paquete se instalan paquetes que forman el denominado núcleo de tidyverse (se cargan con `library(tidyverse)`):

* [ggplot2](https://ggplot2.tidyverse.org): visualización de datos.
* [dplyr](https://dplyr.tidyverse.org): manipulación de datos.
* [tidyr](https://tidyr.tidyverse.org): reorganización (limpieza) de datos.
* [readr](https://readr.tidyverse.org): importación de datos.
* [tibble](https://tibble.tidyverse.org): tablas de datos (modificación de `data.frame`).
* [purrr](https://purrr.tidyverse.org): programación funcional.
* [stringr](https://github.com/tidyverse/stringr): manipulación de cadenas de texto.
* [forcats](https://github.com/tidyverse/forcats): manipulación de factores.
* [lubridate](https://github.com/tidyverse/lubridate): manipulación de fechas y horas.

y un conjunto de paquetes recomendados:



