# Referencias {-}

Fernández-Casal R., Costa J. y Oviedo de la Fuente, M. (2021). *[Aprendizaje Estadístico](https://rubenfcasal.github.io/aprendizaje_estadistico)*. [github](https://github.com/rubenfcasal/aprendizaje_estadistico).

Fernández-Casal R., Roca-Pardiñas J., Costa J. y Oviedo-de la Fuente M. (2023). *[Introducción al Análisis de Datos con R](https://rubenfcasal.github.io/intror)*. ISBN: 978-84-09-41823-7. [github](https://github.com/rubenfcasal/intror).

Grolemund, G. (2014). *[Hands-on programming with R: Write your own functions and simulations](https://rstudio-education.github.io/hopr)*, [O'Reilly](http://shop.oreilly.com/product/0636920028574.do).

Kuhn, M. y Silge, J. (2022). *[Tidy Modeling with R](https://www.tmwr.org)*. [O'Reill](https://amzn.to/35Hn96s).

Matloff, N. (2011). *The art of R programming: A tour of statistical software design*, [No Starch Press](https://www.nostarch.com/artofr.htm).

Wickham, H. (2015). *[R packages: organize, test, document, and share your code](http://r-pkgs.had.co.nz/)* (actualmente 2ª edición en desarrollo con H. Bryan), [O'Reilly, 1ª edición](http://shop.oreilly.com/product/0636920034421.do).

Wickham, H. (2019). *[Advanced R, 2ª edición](https://adv-r.hadley.nz/)*, [Chapman & Hall](https://www.amazon.com/dp/0815384572), [1ª edición.](http://adv-r.had.co.nz/).

Wickham, H., y Grolemund, G. (2016). *[R for data science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz)*, [online-castellano](https://es.r4ds.hadley.nz), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do).


NOTA: En la bibliografía complementaria se incluyen algunas de estas referencias, y una selección de libros en abierto, organizados por temas.


## Bibliografía por temas {-}

***En preparación...***

A continuación se muestra una selección de ***libros en abierto*** que considero que pueden resultar de utilidad.
Para referencias adicionales recomiendo consultar:

- Baruffa, O. (2022). *[Big Book of R](https://www.bigbookofr.com)*: Your last-ever bookmark (hopefully...).


### Iniciación a la programación en R {-}

- Wickham, H., y Grolemund, G. (2016). *[R for data science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz)*, [online-castellano](https://es.r4ds.hadley.nz), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do).

- Grolemund, G. (2014). *[Hands-on programming with R: Write your own functions and simulations](https://rstudio-education.github.io/hopr)*, [O'Reilly](http://shop.oreilly.com/product/0636920028574.do).

- Fernández-Casal R., Roca-Pardiñas J., Costa J., y Oviedo de la Fuente, M. (2022). *[Introducción al Análisis de Datos con R](https://rubenfcasal.github.io/intror)*. [github](https://github.com/rubenfcasal/intror).


### Programación avanzada en R {-}

- Wickham, H. (2019). *[Advanced R, 2ª edición](https://adv-r.hadley.nz/)*, [Chapman & Hall](https://www.amazon.com/dp/0815384572), [1ª edición.](http://adv-r.had.co.nz/).

- Wickham, H. (2015). *[R packages: organize, test, document, and share your code](http://r-pkgs.had.co.nz/)* (actualmente 2ª edición en desarrollo con H. Bryan), [O'Reilly, 1ª edición](http://shop.oreilly.com/product/0636920034421.do).

### Regresión y aprendizaje estadístico {-}

- Fernández-Casal R., Costa J. y Oviedo de la Fuente, M. (2021). *[Aprendizaje Estadístico](https://rubenfcasal.github.io/aprendizaje_estadistico)*. [github](https://github.com/rubenfcasal/aprendizaje_estadistico).

- Kuhn, M., y Silge, J. (2022). *[Tidy Modeling with R](https://www.tmwr.org)*, [O'Reilly](https://www.oreilly.com/library/view/tidy-modeling-with/9781492096474).

- Fernández-Casal R., Cao R. y Costa J. (2023). *[Técnicas de Simulación y Remuestreo](https://rubenfcasal.github.io/simbook)*  ([github](https://github.com/rubenfcasal/simbook)). La anterior edición (Fernández-Casal R. y Cao R., 2022, *Simulación Estadística*) está disponible en la rama *[primera_edicion](https://github.com/rubenfcasal/simbook/tree/primera_edicion)*.


### Datos temporales y espaciales {-}

- Fernández-Casal R. y Cotos-Yáñez T.R. (2021). *[Estadística Espacial con R](https://rubenfcasal.github.io/estadistica_espacial)*. [github](https://github.com/rubenfcasal/estadistica_espacial). 

- Hyndman, R.J., y Athanasopoulos, G. (2021). *[Forecasting: principles and practice](https://otexts.com/fpp3)*. [OTexts](https://www.amazon.es/dp/0987507133).

- Lovelace, R., Nowosad, J., y Muenchow, J. (2019). *[Geocomputation with R](https://geocompr.robinlovelace.net)*. [CRC](https://www.routledge.com/9781138304512).

- Moraga, P. (2019). *[Geospatial health data: Modeling and visualization with R-INLA and shiny](https://www.paulamoraga.com/book-geospatial)*, [CRC](https://www.routledge.com/9780367357955).
    
- Pebesma, E., y Bivand, R. (2021). *[Spatial Data Science](https://keen-swartz-3146c4.netlify.app)*.
  
    
### Rmarkdown {-}

- Fernández-Casal, R. y Cotos-Yáñez, T.R. (2018). *[Escritura de libros con bookdown](https://rubenfcasal.github.io/bookdown_intro)*,   [github](https://github.com/rubenfcasal/bookdown_intro). Incluye un apéndice con una [Introducción a RMarkdown](https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html). 


## Enlaces {.unnumbered #links}


***Repositorio***: [rubenfcasal/book_notasr](https://github.com/rubenfcasal/book_notasr)

***Recursos para el aprendizaje de R***: En este [post](https://rubenfcasal.github.io/post/ayuda-y-recursos-para-el-aprendizaje-de-r) se muestran algunos recursos que pueden ser útiles para el aprendizaje de R y la obtención de ayuda.

[***Bookdown***](https://bookdown.org):

[***Introducción a RMarkdown***](https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html). 

[***Posit (RStudio)***](https://posit.co)

* [Blog](https://posit.co/blog)

* [Videos](https://posit.co/resources/videos)

* [Chuletas (Cheatsheets)](https://posit.co/resources/cheatsheets)

* [***tidyverse***](https://www.tidyverse.org/):

    - [dplyr](https://dplyr.tidyverse.org)
    
    - [tibble](https://tibble.tidyverse.org)
    
    - [tidyr](https://tidyr.tidyverse.org)
    
    - [stringr](https://stringr.tidyverse.org)
    
    - [readr](https://readr.tidyverse.org)
    
    - [Best Practices in Working with Databases](https://solutions.posit.co/connections/db)
    
* [tidymodels](https://www.tidymodels.org)    

* [sparklyr](https://spark.rstudio.com/)

* [shiny](http://shiny.rstudio.com)
